services:
  mcpanel:
    image: milesmuehlbach/mcpanel:latest
    container_name: mcpanel
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./minecraft:/app/minecraft
